"""Data contracts, request/response models, and domain schemas."""

from typing import Any, Literal

from pydantic import BaseModel, Field

# Domain literals
GenderType = Literal["men", "women", "unisex", "unknown"]
AgeGroupType = Literal["adult", "kids"]
SlotType = Literal["top", "bottom", "full_body", "footwear", "accessory", "innerwear", "unknown"]
AccessoryType = Literal[
    "hat",
    "eyewear",
    "bag",
    "scarf",
    "belt",
    "watch",
    "jewelry",
    "body_jewelry",
    "hair",
    "socks",
    "gloves",
    "other",
]
SearchMode = Literal["products", "product", "outfit"]


class RawProductMetadata(BaseModel):
    """Raw product metadata matching the Amazon Fashion dataset schema."""

    parent_asin: str
    title: str | None = None
    features: list[str] | None = Field(default_factory=list)
    description: list[str] | str | None = Field(default_factory=list)
    price: float | None = None
    store: str | None = None
    average_rating: float | None = None
    rating_number: int | None = None
    details: dict[str, Any] | None = Field(default_factory=dict)
    images: list[dict[str, Any]] | None = Field(default_factory=list)
    categories: list[str] | None = Field(default_factory=list)
    videos: list[dict[str, Any]] | None = Field(default_factory=list)
    bought_together: Any | None = None


class RawReviewRecord(BaseModel):
    """Raw review record from Amazon Reviews dataset."""

    parent_asin: str
    text: str | None = None
    rating: float | None = None
    helpful_vote: int = 0


class Product(BaseModel):
    """Catalog product domain model stored in SQLite."""

    parent_asin: str
    title: str
    store: str | None = None
    price: float | None = None
    average_rating: float | None = None
    rating_number: int | None = None
    quality_score: float = 0.0
    image_url: str | None = None
    gender: str = "unknown"
    age_group: str = "adult"
    slot: str = "unknown"
    accessory_type: str | None = None
    colors: list[str] = Field(default_factory=list)
    seasons: list[str] = Field(default_factory=list)
    occasions: list[str] = Field(default_factory=list)
    features: list[str] = Field(default_factory=list)
    description: str | None = None
    review_snippets: list[str] = Field(default_factory=list)
    search_text: str = ""
    version: int = 1
    created_at: str = ""
    updated_at: str = ""
    is_deleted: bool = False


class ParsedQuery(BaseModel):
    """Structured query representation generated by query parser."""

    occasion: str | None = None
    season: str | None = None
    gender: str | None = None
    age_group: str | None = "adult"
    max_price: float | None = None
    min_price: float | None = None
    brand: str | None = None
    colors: list[str] = Field(default_factory=list)
    slots: list[str] = Field(default_factory=list)
    language: str = "en"
    normalized_query_en: str
    is_fashion_query: bool = True
    warnings: list[str] = Field(default_factory=list)


class SearchRequest(BaseModel):
    """Incoming search request schema."""

    query: str = Field(..., min_length=1, max_length=500)
    top_k: int = Field(default=10, ge=1, le=50)
    mode: SearchMode = "product"


class SearchResultItem(BaseModel):
    """A single ranked product in the search results.

    Note:
        `score` is the final calibrated rank score [0, 1] incorporating normalized RRF,
        quality boost, and soft matching boosts.
        `similarity` is the true cosine similarity between the query embedding and the
        product embedding.
    """

    product_id: str
    title: str
    price: float | None = None
    brand: str | None = None
    image_url: str | None = None
    slot: str
    accessory_type: str | None = None
    gender: str = "unknown"
    age_group: str = "adult"
    score: float = Field(
        description="Calibrated score [0, 1] combining normalized RRF, quality, and boosts."
    )
    similarity: float = Field(
        default=0.0,
        description="Cosine similarity between query embedding and product embedding.",
    )
    reason: str | None = None


class OutfitPayload(BaseModel):
    """Structured outfit composition inner payload."""

    items: list[SearchResultItem]
    total_price: float
    complete: bool
    missing_slots: list[str] = Field(default_factory=list)
    template: str


class SearchMeta(BaseModel):
    """Metadata accompanying search response."""

    parsed_filters: dict[str, Any]
    used_fallback: bool
    latency_ms: float
    index_version: int
    excluded_by_filters: int
    duplicates_collapsed: int = 0
    low_confidence: bool = False
    warnings: list[str] = Field(default_factory=list)


class OutfitResponse(BaseModel):
    """Structured outfit response."""

    outfit: OutfitPayload | None = None
    meta: SearchMeta
    message: str | None = None
    suggested_queries: list[str] | None = None


class SearchResponse(BaseModel):
    """Complete response returned by POST /search."""

    results: list[SearchResultItem]
    meta: SearchMeta
    outfit: OutfitResponse | None = None
    message: str | None = None
    suggested_queries: list[str] | None = None


class ProductBatchRequest(BaseModel):
    """Batch ingestion request payload."""

    products: list[dict[str, Any]] = Field(
        ...,
        min_length=1,
        max_length=500,
        description="List of raw product metadata records (max 500 per request).",
    )


class ProductBatchItemResult(BaseModel):
    """Result for an individual product record within a batch ingestion request."""

    parent_asin: str
    status: Literal["created", "updated", "rejected"]
    version: int | None = None
    reason: str | None = None


class ProductBatchResponse(BaseModel):
    """Response returned by POST /products."""

    accepted_count: int
    rejected_count: int
    index_version: int
    items: list[ProductBatchItemResult]


class ProductDeleteResponse(BaseModel):
    """Response returned by DELETE /products/{id}."""

    product_id: str
    status: Literal["deleted", "already_deleted"]
    index_version: int


class HealthResponse(BaseModel):
    """Liveness and readiness health check response."""

    status: str
    index_loaded: bool
    catalog_reachable: bool
    llm_status: str
    index_size: int
    catalog_size: int


class MetricsResponse(BaseModel):
    """System and operational metrics response."""

    request_count: int
    requests_by_endpoint: dict[str, int]
    p50_latency_ms: float
    p95_latency_ms: float
    p99_latency_ms: float
    fallback_rate: float
    zero_result_rate: float
    low_confidence_rate: float
    query_cache_hit_rate: float
    parse_cache_hit_rate: float
    warnings_count: dict[str, int]
    llm_status: str
    index_size: int
    index_version: int
    ingestion_accepted: int
    ingestion_rejected_by_reason: dict[str, int]
    last_batch_duration_seconds: float | None = None
