"""Gemini LLM Client implementation using official google-genai SDK."""

import logging
from typing import Any

from app.config import settings
from app.exceptions import ConfigurationError, LLMError

logger = logging.getLogger(__name__)


class GeminiClient:
    """LLM client wrapping Google Gemini API via google-genai SDK."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        """Initialize Gemini client with API key and model name.

        Args:
            api_key: Gemini API Key. Defaults to settings.llm_api_key.
            model: Gemini model identifier. Defaults to settings.llm_model.
        """
        self.api_key = api_key if api_key is not None else settings.llm_api_key
        self.model = model if model is not None else settings.llm_model
        self._client: Any = None

    def _get_client(self) -> Any:
        """Get or lazily initialize the Google GenAI Client."""
        if not self.api_key or not self.model:
            raise ConfigurationError(
                "LLM_API_KEY and LLM_MODEL must be configured in environment or .env "
                "to execute LLM queries."
            )
        if self._client is None:
            try:
                from google import genai

                self._client = genai.Client(api_key=self.api_key)
            except Exception as e:
                raise ConfigurationError(f"Failed to initialize google.genai Client: {e}") from e
        return self._client

    def complete_json(self, system: str, user: str, timeout: float = 3.0) -> str:
        """Execute JSON completion with Gemini.

        Args:
            system: System instructions.
            user: User content / query string.
            timeout: Max allowed execution timeout in seconds.

        Returns:
            String text generated by Gemini.

        Raises:
            TimeoutError: If request times out.
            LLMError: If LLM call fails.
            ConfigurationError: If credentials or model are missing.
        """
        client = self._get_client()
        try:
            from google.genai import types

            config = types.GenerateContentConfig(
                system_instruction=system,
                response_mime_type="application/json",
                temperature=0.0,
            )

            # Note: google-genai models.generate_content
            response = client.models.generate_content(
                model=self.model,
                contents=user,
                config=config,
            )
            if not response.text:
                raise LLMError("Gemini returned an empty response.")
            return str(response.text).strip()

        except ConfigurationError:
            raise
        except TimeoutError as te:
            logger.warning("Gemini completion timed out after %s seconds: %s", timeout, te)
            raise
        except Exception as e:
            err_msg = str(e)
            if "deadline" in err_msg.lower() or "timeout" in err_msg.lower():
                raise TimeoutError(f"Gemini API timed out: {e}") from e
            logger.error("Gemini completion failed: %s", e)
            raise LLMError(f"Gemini API error: {e}") from e
